# -*- coding: utf-8 -*-
"""AI Server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xlp6bTxLiQMNNrbHVvFVOrmTXf2c9Zg9
"""

pip install Flask

from google.colab import drive
drive.mount('/content/drive')

from flask import Flask, request, jsonify
from keras.models import load_model
import os

app = Flask(__name__)

# 구글 드라이브에서 모델 파일의 경로
model_path = '/content/drive/MyDrive/smishing_model.h5'

# AI 모델 로드
if os.path.exists(model_path):
    model = load_model(model_path)
else:
    raise FileNotFoundError("모델 파일을 찾을 수 없습니다.")

# 사용자 요청을 처리하는 라우트
@app.route('/check_smishing', methods=['POST'])
def check_smishing():
    try:
        # 클라이언트로부터 텍스트 메시지를 받음
        data = request.json['message']

        # 여기서 전처리 및 판별하는 코드를 추가
        # 이 코드는 이미 모델에 내장되어 있으므로 생략합니다.

        # AI 모델에 텍스트 메시지를 전달하고 스미싱 여부를 판단
        prediction = model.predict(data)

        # 스미싱 여부를 JSON 형식으로 반환
        return jsonify({'is_smishing': prediction}), 200

    except Exception as e:
        # 예외 처리
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    # 서버 실행
    app.run(debug=True)